name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          HEADLESS: "1"
        run: |
          pytest tests/test_login_working.py
          pytest tests/test_login_broken_heals.py

      - name: Summarize heal events
        if: always()
        run: |
          python scripts/summarize_heals.py

      - name: Upload heal artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: heal-artifacts
          path: artifacts/heals/**