
name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run pytest (headless)
        env:
          HEADLESS: "1"
        run: |
          . .venv/bin/activate
          pytest

      - name: Summarize heals
        if: always()
        run: |
          . .venv/bin/activate
          python scripts/summarize_heals.py

      - name: Upload artifacts (heal logs & summary)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: heal-artifacts
          path: artifacts/heals/**
